### PR TITLE
Installation on Intel-based Macs

### PR DESCRIPTION
**Pull request by PhilippHoellmer**
This allows to install pele on Intel-based Macs.

Besides the necessary changes in the mac-specific installation procedure, I also cleaned up the README.rst file a bit and resolved one simple TODO in the setup_with_cmake.py file. Also, I allowed for the develop option after the distutils setup so that one does not need to set the PYTHONPATH.

I was careful that everything is unchanged if run on Linux but this should be checked. 

I also added another job in the GitHub workflow that runs on MacOs instead of Ubuntu. However, I could not test this part because one cannot trigger this workflow manually at the moment. Do you know how we could check the new workflow before merging the pull request?

### CODE REVIEW

**Comment by PhilippHoellmer** [comment]
Okay, I see that the new GitHub workflows were triggered by this pull request. We will see if that works out.

**Comment by spraharsh** [comment]
You can also use https://github.com/nektos/act to run the workflow locally to check

**Comment by PhilippHoellmer** [comment]
That is good to know, thank you for the link. The Mac job already failed so I will fix that. Fortunately, it is already an error in the setup of the conda environment.

**Comment by PhilippHoellmer** [comment]
There were some minor problems because the MacOs runner in the GitHub workflow actually uses a two-year old MacOs version. But all problems are fixed now and all tests are green on both Linux and MacOs.

I guess the most important changes to review are within the setup_with_cmake.py and the README.rst files.

**Comment by PhilippHoellmer** [comment]
I just pushed two final commits with some minor changes that are necessary on Apple silicon. With this, pele can be installed on both Intel-based Macs and the new Apple silicon Macs! Unfortunately, there is no free GitHub Workflow available that checks the installation on Apple silicon Macs but all tests are green on my machine.

**Comment by spraharsh** [comment]
Awesome! Thank you so much for this!

**Pull request merged**
